platform:
  - x86
#  - x64

environment:
  matrix:
    - BUILD_TYPE: nmake


build_script:
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - nmake /f windows.mk
  - cd core
  - nmake /f W_makefile.mk
  - cd ..

test_script:
  - core\pubnub_proxy_NTLM_test
  - windows\pubnub_fntest
  - openssl\pubnub_fntest
  - cpp\fntest_runner
  - cpp\openssl\fntest_runner

deploy: off
