platform:
  - x86
#  - x64

environment:
  matrix:
    - BUILD_TYPE: nmake


build_script:
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - nmake /f windows.mk
  - windows/pubnub_fntest
  - openssl/pubnub_fntest

deploy: off
