language: c
os:
  - linux
  - osx
dist: trusty
sudo: false
compiler:
  - clang
  - gcc
install:
  - pip install gcovr
script:
  - git clone https://github.com/cgreen-devs/cgreen.git
  - cd cgreen
  - make
  - cd ..
  - cd core
  - make
  - cd ..
  - make -f posix.mk
  - posix/pubnub_fntest
  - openssl/pubnub_fntest
