language: c
os:
  - linux
  - osx
dist: trusty
sudo: false
compiler:
  - clang
  - gcc
script:
  - git clone https://github.com/cgreen-devs/cgreen.git
  - cd cgreen && cmake && make
  - make -f posix.mk
  - posix/pubnub_fntest
  - openssl/pubnub_fntest
